# Generated by Django 2.1.3 on 2018-12-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='alumno-x', max_length=255),
        ),
    ]
