# Generated by Django 2.1.3 on 2018-12-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_auto_20181207_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.CharField(default='999999', max_length=255),
        ),
    ]
