# Generated by Django 2.1.3 on 2018-12-08 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_auto_20181208_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
