# Generated by Django 2.1.3 on 2018-12-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_materia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
